### ISSUE TITLE
bug: prometheus remote write时崩溃

### ISSUE THREAD

**Issue by Starfa** [clickvisual/clickvisual#1050]
**Describe the bug**

**ClickVisual Running Environment**
Please provide the following information:

- ClickVisual version:
v1.0.0-rc7

- ClickVisual.LOG:
```
./clickvisual --config config/default.toml
2023/09/15 08:12:37 PreRun args:  []
2023/09/15 08:12:37 ConfigFile config/default.toml
2023/09/15 08:12:37 EGO_CONFIG_PATH: 
2023/09/15 08:12:37 File config/default.toml
2023/09/15 08:12:37 Run args:  []

    _/_/_/_/    _/_/_/    _/_/   
   _/        _/        _/    _/   
  _/_/_/    _/  _/_/  _/    _/    
 _/        _/    _/  _/    _/     
_/_/_/_/    _/_/_/    _/_/  

Welcome to Ego, starting application ...

panic: invalid size

goroutine 92 [running]:
github.com/ClickHouse/ch-go/proto.(*ColFixedStr).Append(...)
        /home/runner/go/pkg/mod/github.com/!click!house/ch-go@v0.47.3/proto/col_fixed_str.go:64
github.com/ClickHouse/clickhouse-go/v2/lib/column.(*FixedString).AppendRow(0xc001a90030, {0x278bc00?, 0xc002020060})
        /home/runner/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/lib/column/fixed_string.go:158 +0x32c
github.com/ClickHouse/clickhouse-go/v2/lib/column.(*Array).append(0xc000508660, {0x278bc00?, 0xc001351780?, 0x8?}, 0x0?)
        /home/runner/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/lib/column/array.go:174 +0xad
github.com/ClickHouse/clickhouse-go/v2/lib/column.(*Array).append(0xc000508660, {0x2729be0?, 0xc0005e8060?, 0x38?}, 0x0)
        /home/runner/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/lib/column/array.go:165 +0x1ef
github.com/ClickHouse/clickhouse-go/v2/lib/column.(*Array).AppendRow(0xc000508660, {0x2729be0?, 0xc0005e8060?})
        /home/runner/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/lib/column/array.go:154 +0x2f4
github.com/ClickHouse/clickhouse-go/v2/lib/proto.(*Block).Append(0xc0014b0000, {0xc00201e0f0?, 0x5, 0x50?})
        /home/runner/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/lib/proto/block.go:59 +0x1a7
github.com/ClickHouse/clickhouse-go/v2.(*batch).Append(0xc00201e050, {0xc00201e0f0?, 0x7f88b46e7f18?, 0x50?})
        /home/runner/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/conn_batch.go:93 +0x34
github.com/ClickHouse/clickhouse-go/v2.(*stdBatch).Exec(0xc002020030, {0xc00201e0a0, 0x5, 0x28efae0?})
        /home/runner/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/clickhouse_std.go:231 +0x77
github.com/ClickHouse/clickhouse-go/v2.(*stdBatch).ExecContext(0x0?, {0x41466f0?, 0xc002020030?}, {0xc000c4c000, 0x5, 0xc0012f0000?})
        /home/runner/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/clickhouse_std.go:242 +0x7c
database/sql.ctxDriverStmtExec({0x4145e30, 0xc00013e000}, {0x41466f0, 0xc002020030}, {0xc000c4c000?, 0x5, 0x5})
        /opt/hostedtoolcache/go/1.18.10/x64/src/database/sql/ctxutil.go:65 +0xcc
database/sql.resultFromStatement({0x4145e30, 0xc00013e000}, {0x4135a20, 0xc0012f0000}, 0xc0014b0140, {0xc000463f80, 0x5, 0x5})
        /opt/hostedtoolcache/go/1.18.10/x64/src/database/sql/sql.go:2663 +0x145
database/sql.(*Stmt).ExecContext(0xc0004ee090, {0x4145e30, 0xc00013e000}, {0xc000463f80, 0x5, 0x5})
        /opt/hostedtoolcache/go/1.18.10/x64/src/database/sql/sql.go:2636 +0x1fd
database/sql.(*Stmt).Exec(...)
        /opt/hostedtoolcache/go/1.18.10/x64/src/database/sql/sql.go:2651
github.com/clickvisual/prom2click.(*promWriter).Start.func1()
        /home/runner/go/pkg/mod/github.com/clickvisual/prom2click@v0.0.4-0.20230725081057-8faff41f6c43/prom_writer.go:182 +0x1049
created by github.com/clickvisual/prom2click.(*promWriter).Start
        /home/runner/go/pkg/mod/github.com/clickvisual/prom2click@v0.0.4-0.20230725081057-8faff41f6c43/prom_writer.go:134 +0x56
```

**Comment by kl7sn** [comment]
可能是 clickhouse 版本兼容问题，你这边使用的 clickhouse 是什么版本
